export const TOWER_TYPES = {
  arrow: {
    name: 'Arrow',
    icon: '🏹',
    cost: 50,
    damage: 10,
    range: 3,
    fireRate: 1.0,
    projectileSpeed: 8,
    projectileColor: 0xffd700,
    color: 0x44aa99,
    splash: 0,
    slow: 0,
    slowDuration: 0,
    chain: 0,
    upgradeCost: (level) => Math.floor(50 * Math.pow(1.5, level)),
    upgradeDamage: (level) => Math.floor(10 * Math.pow(1.3, level)),
    sprite: {
      base: 'archer_level_',
      units: {
        1: { idle: 'archer_unit1_idle_s', attack: 'archer_unit1_idle_s' },
        2: { idle: 'archer_unit2_idle_s', attack: 'archer_unit2_idle_s' },
        3: { idle: 'archer_unit3_idle_s', attack: 'archer_unit3_idle_s' },
      },
      projectile: 'arrow_1',
    },
  },
  cannon: {
    name: 'Cannon',
    icon: '💣',
    cost: 100,
    damage: 30,
    range: 2.5,
    fireRate: 0.5,
    projectileSpeed: 5,
    projectileColor: 0xff6b6b,
    color: 0xcc5555,
    splash: 1.2,
    slow: 0,
    slowDuration: 0,
    chain: 0,
    upgradeCost: (level) => Math.floor(100 * Math.pow(1.5, level)),
    upgradeDamage: (level) => Math.floor(30 * Math.pow(1.3, level)),
    sprite: {
      base: 'stone_base',
      units: { 1: { idle: 'archer_unit2_idle_s' } },
      tint: 0xff6b6b,
    },
  },
  ice: {
    name: 'Ice',
    icon: '❄️',
    cost: 75,
    damage: 5,
    range: 2.5,
    fireRate: 0.8,
    projectileSpeed: 6,
    projectileColor: 0x88ccff,
    color: 0x5588cc,
    splash: 0,
    slow: 0.5,
    slowDuration: 2.0,
    chain: 0,
    upgradeCost: (level) => Math.floor(75 * Math.pow(1.5, level)),
    upgradeDamage: (level) => Math.floor(5 * Math.pow(1.3, level)),
    sprite: {
      base: 'stone_base',
      units: { 1: { idle: 'archer_unit3_idle_s' } },
      tint: 0x88ccff,
    },
  },
  lightning: {
    name: 'Lightning',
    icon: '⚡',
    cost: 150,
    damage: 20,
    range: 3.5,
    fireRate: 1.2,
    projectileSpeed: 15,
    projectileColor: 0xffee88,
    color: 0xcccc88,
    splash: 0,
    slow: 0,
    slowDuration: 0,
    chain: 2,
    upgradeCost: (level) => Math.floor(150 * Math.pow(1.5, level)),
    upgradeDamage: (level) => Math.floor(20 * Math.pow(1.3, level)),
    sprite: {
      base: 'stone_base',
      units: { 1: { idle: 'archer_unit1_idle_s' } },
      tint: 0xffee88,
    },
  },
};

export default TOWER_TYPES;
